baseURL = 'http://localhost:1313/'
languageCode = 'cs-cz'
title = 'Portfolio Davida Lokaje'
theme = 'ananke'

# âš™ï¸ NastavenÃ­ vÃ½chozÃ­ho zobrazenÃ­
[pagination]
  pagerSize = 10

# ğŸ“Œ NavigaÄnÃ­ menu
[[menu.main]]
  identifier = "uvod"
  name = "Ãšvod"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "o-mne"
  name = "O mnÄ›"
  url = "/o-mne/"
  weight = 2

[[menu.main]]
  identifier = "ukoly"
  name = "Ãškoly"
  url = "/posts/"
  weight = 3

[[menu.main]]
  identifier = "finalni-projekt"
  name = "FinÃ¡lnÃ­ projekt"
  url = "/posts/finalni-projekt/"
  weight = 4